services:
    exs_tracking.awe_manager:
        class: 'EXS\LanderTrackingAWEBundle\Service\TrackingParameterManager\AweTrackingParameterManager'
        tags:
            - { name: 'exs_tracking.parameter_extracter' }
            - { name: 'exs_tracking.parameter_formatter' }
